# Generated by Django 4.1.7 on 2023-03-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='unique_id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='files',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
